### PR TITLE
Sprint6 task2 pagination

### PR DESCRIPTION
**Pull request by iAcay**
Hey! The code which is below was implemented in order to meet the acceptance criterias of the second task in sprint no. 6.

AC in this task:
-- An employee sees no more than three rewards on one page
-- There're links to other pages under the rewards list
-- There is the exact number of rewards pages, so no link leads to an empty page
-- There's a system spec for moving between pages of the rewards list

For pagination I have decided to use will_paginate gem. Link to its documentation: https://github.com/mislav/will_paginate

https://user-images.githubusercontent.com/96024046/180996926-581ef449-dc7c-4d4e-bb8e-7f62b4e4c31a.mov

### CODE REVIEW

**Review by piowit — COMMENTED** [review]
Looks good to me :) 🍰

**Comment by iAcay** [comment]
> Looks good to me :) 🍰

Thanks for review! :)

**Review by ciejj — APPROVED** [review]
Looks good - well done, nothing toa dd from my side :)

**Comment by iAcay** [comment]
> Looks good - well done, nothing toa dd from my side :)

Thanks! 👍

**Pull request merged**
